# Generated by Django 5.1.4 on 2025-01-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_alter_pizzamodel_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzamodel',
            options={'ordering': ('-id',)},
        ),
    ]
