# Generated by Django 5.1.4 on 2024-12-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['-id']},
        ),
    ]
